"""add-cascade_delete

Revision ID: 4945c3f6d890
Revises: 873683dc9509
Create Date: 2024-12-27 16:01:15.856118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4945c3f6d890'
down_revision: Union[str, None] = '873683dc9509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'release_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('treatments_therapist_id_fkey', 'treatments', type_='foreignkey')
    op.create_foreign_key(None, 'treatments', 'users', ['therapist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatments', type_='foreignkey')
    op.create_foreign_key('treatments_therapist_id_fkey', 'treatments', 'users', ['therapist_id'], ['id'])
    op.alter_column('patients', 'release_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
