"""added on delete for patients

Revision ID: ecb499276274
Revises: 04ffbb73bb77
Create Date: 2024-12-28 20:56:02.900228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb499276274'
down_revision: Union[str, None] = '04ffbb73bb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('treatments_patient_id_fkey', 'treatments', type_='foreignkey')
    op.create_foreign_key(None, 'treatments', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatments', type_='foreignkey')
    op.create_foreign_key('treatments_patient_id_fkey', 'treatments', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###
